[WorldGen]
chunkHeight = 64
chunkWidth = 64
surfaceMin = 30
surfaceMax = 60
dirtMin = 2
dirtMax = 5
offsetX = 0
offsetY = 0
seed = 0

[Physics]
GRAVITY = 30.53 #in blocks/per second
FALL_SPEED = 20.1 #12.4
safe_step = 30

[Player]
health = 100
speed = 2 #in blocks/per second
jumpPower = 2 #in blocks/per second
miningSpeed = 35 #durability removed/per second

[Window]
TILE_SIZE = 121
gameTitle = "Boannt"
